MUMScrum.Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MUMScrum.Data;
using MUMScrum.Model.Model;
using MUMScrum.Service;

namespace MUMScrum.Web.Controllers
{
    public class ProjectController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private IProjectService _projectService;
        private IUserstoryService _userStoryService;
        private IEmployeeService _employeeService;

        public ProjectController(IProjectService projectService, IUserstoryService userstoryService, IEmployeeService employeeService)
        {
            this._projectService = projectService;
            this._userStoryService = userstoryService;
            this._employeeService = employeeService;
        }


        // GET: Project
        public ActionResult Index()
        {
            var projects = this._projectService.GetAll().Include(p => p.CreatedBy).Include(p => p.ModifiedBy).Include(p => p.ProductOwner);
            return View(projects.ToList());
        }

        // GET: Project/Details/5
        public ActionResult UserStories(int id)
        {
            Project project = this._projectService.GetById(id);

            if(project.userStoryList.Count==0)
            {
                project=new Project();
                project.userStoryList = new List<UserStory>();
            }     
            return View(project);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            //ViewBag.CreatedById = new SelectList(db.Employees, "EmployeeId", "Name");
            //ViewBag.ModifiedById = new SelectList(db.Employees, "EmployeeId", "Name");            
            ViewBag.EmployeeId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name");
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,StartDate,EndDate,EmployeeId,CreatedById,ModifiedById,CreatedDate,ModifiedDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                this._projectService.Create(project);
                return RedirectToAction("Index");
            }

            //ViewBag.CreatedById = new SelectList(db.Employees, "EmployeeId", "Name", project.CreatedById);
            //ViewBag.ModifiedById = new SelectList(db.Employees, "EmployeeId", "Name", project.ModifiedById);
            //ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "Name", project.EmployeeId);
            return View(project);
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int id)
        {
            Project project =_projectService.GetById(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            //ViewBag.CreatedById = new SelectList(db.Employees, "EmployeeId", "Name", project.CreatedById);
            //ViewBag.ModifiedById = new SelectList(db.Employees, "EmployeeId", "Name", project.ModifiedById);
           
            ViewBag.EmployeeId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", project.EmployeeId);
            return View(project);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,StartDate,EndDate,EmployeeId,CreatedById,ModifiedById,CreatedDate,ModifiedDate")] Project project)
        {
            if (ModelState.IsValid)
            {
                _projectService.Update(project);
                return RedirectToAction("Index");
            }
            //ViewBag.CreatedById = new SelectList(db.Employees, "EmployeeId", "Name", project.CreatedById);
            //ViewBag.ModifiedById = new SelectList(db.Employees, "EmployeeId", "Name", project.ModifiedById);
            //ViewBag.EmployeeId = new SelectList(db.Employees, "EmployeeId", "Name", project.EmployeeId);
            return View(project);
        }

        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            Project project = _projectService.GetById(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project pr = _projectService.GetById(id);
            _projectService.Delete(pr);
            return RedirectToAction("Index");
        }
    }
}

MUMScrum.Web/Controllers/UserStoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MUMScrum.Data;
using MUMScrum.Model.Model;
using MUMScrum.Service;
using MUMScrum.Model.ViewModel;
using MUMScrum.Model.ENUMS;
using MUMScrum.Model.SessionModel;

namespace MUMScrum.Web.Controllers
{
    public class UserStoryController : Controller
    {
        private IUserstoryService _userstoryService;
        private IEmployeeService _employeeService;
        private ISprintService _sprintService;
        private IReleaseBacklogService _releaseBacklogService;
        private IProjectService _projectService;

        public UserStoryController(IUserstoryService userstoryService,
            IEmployeeService employeeService,
            ISprintService sprintService,
            IReleaseBacklogService releaseBacklogService,
            IProjectService projectService)
        {
            this._userstoryService = userstoryService;
            this._employeeService = employeeService;
            this._sprintService = sprintService;
            this._releaseBacklogService = releaseBacklogService;
            this._projectService = projectService;
        }
        // GET: UserStory
        public ActionResult Index()
        {
            var userStorys = _userstoryService.GetAll().Include(u => u.Developer).Include(u => u.project).Include(u => u.ReleaseBacklog).Include(u => u.Sprint).Include(u => u.Tester);
            if (SessionModel.LoginUser.RoleId == RoleEnum.Developer)
            {
                userStorys = _userstoryService.GetAll().Include(u => u.Developer).Include(u => u.project).Include(u => u.ReleaseBacklog).Include(u => u.Sprint).Include(u => u.Tester).Where(m => m.DeveloperId == SessionModel.LoginUser.EmployeeId);
            }
            if (SessionModel.LoginUser.RoleId == RoleEnum.Tester)
            {
                userStorys = _userstoryService.GetAll().Include(u => u.Developer).Include(u => u.project).Include(u => u.ReleaseBacklog).Include(u => u.Sprint).Include(u => u.Tester).Where(m => m.TesterId == SessionModel.LoginUser.EmployeeId);
            }
            return View(userStorys.ToList());
        }

        // GET: UserStory/Details/5
        public ActionResult Details(int id)
        {
            UserStory userStory = _userstoryService.GetById(id);
            if (userStory == null)
            {
                return HttpNotFound();
            }
            return View(userStory);
        }

        // GET: UserStory/Create
        public ActionResult Create()
        {
            ViewBag.ProjectId = new SelectList(_projectService.GetAll(), "Id", "Name");
            //    ViewBag.CreatedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name");
            //   ViewBag.DeveloperId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name");
            //  ViewBag.ModifiedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name");
            ViewBag.ReleaseBacklogId = new SelectList(_releaseBacklogService.GetAll(), "Id", "Name");
            //  ViewBag.SprintId = new SelectList(_sprintService.GetAll(), "Id", "Name");
            //  ViewBag.TesterId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name");
            return View();
        }

        // POST: UserStory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description,UserStoryType,Status,ProjectId,DeveloperId,TesterId,DeveloperEstimate,TesterEstimate,ReleaseBacklogId,SprintId,CreatedById,ModifiedById,CreatedDate,ModifiedDate")] UserStory userStory)
        {
            if (ModelState.IsValid)
            {
                _userstoryService.Create(userStory);
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(_projectService.GetAll(), "Id", "Name", userStory.ProjectId);
            ViewBag.CreatedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.CreatedById);
            ViewBag.DeveloperId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.DeveloperId);
            ViewBag.ModifiedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.ModifiedById);
            ViewBag.ReleaseBacklogId = new SelectList(_releaseBacklogService.GetAll(), "Id", "Name", userStory.ReleaseBacklogId);
            ViewBag.SprintId = new SelectList(_sprintService.GetAll(), "Id", "Name", userStory.SprintId);
            ViewBag.TesterId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.TesterId);
            return View(userStory);
        }

        // GET: UserStory/Edit/5
        public ActionResult Edit(int id)
        {
            UserStory userStory = _userstoryService.GetById(id);
            if (userStory == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = new SelectList(_projectService.GetAll(), "Id", "Name", userStory.ProjectId);
            //ViewBag.CreatedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.CreatedById);
            //ViewBag.DeveloperId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.DeveloperId);
            //ViewBag.ModifiedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.ModifiedById);
            ViewBag.ReleaseBacklogId = new SelectList(_releaseBacklogService.GetAll(), "Id", "Name", userStory.ReleaseBacklogId);
            //ViewBag.SprintId = new SelectList(_sprintService.GetAll(), "Id", "Name", userStory.SprintId);
            //ViewBag.TesterId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.TesterId);
            return View(userStory);
        }

        // POST: UserStory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description,UserStoryType,Status,ProjectId,DeveloperId,TesterId,DeveloperEstimate,TesterEstimate,ReleaseBacklogId,SprintId,CreatedById,ModifiedById,CreatedDate,ModifiedDate")] UserStory userStory)
        {
            if (ModelState.IsValid)
            {
                _userstoryService.Update(userStory);
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(_projectService.GetAll(), "Id", "Name", userStory.ProjectId);
            // ViewBag.CreatedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.CreatedById);
            // ViewBag.DeveloperId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.DeveloperId);
            // ViewBag.ModifiedById = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.ModifiedById);
            ViewBag.ReleaseBacklogId = new SelectList(_releaseBacklogService.GetAll(), "Id", "Name", userStory.ReleaseBacklogId);
            //  ViewBag.SprintId = new SelectList(_sprintService.GetAll(), "Id", "Name", userStory.SprintId);
            //   ViewBag.TesterId = new SelectList(_employeeService.GetAll(), "EmployeeId", "Name", userStory.TesterId);
            return View(userStory);
        }

        // GET: UserStory/Delete/5
        public ActionResult Delete(int id)
        {
            UserStory userStory = _userstoryService.GetById(id);
            if (userStory == null)
            {
                return HttpNotFound();
            }
            return View(userStory);
        }

        // POST: UserStory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserStory userStory = _userstoryService.GetById(id);
            _userstoryService.Delete(userStory);
            return RedirectToAction("Index");
        }

        public ActionResult DeveloperEstimateEffort(int empId, int userStoryId, EmployeeEstimateENUM effortType)
        {
            var Role = SessionModel.LoginUser.RoleId;
            EmployeeEffortEstimation emp = this._userstoryService.GetEffortData(empId, userStoryId, Role, effortType);
            emp.EstimateType = effortType;
            return View(emp);
        }
        [HttpPost]
        public ActionResult DeveloperEstimateEffort(EmployeeEffortEstimation emp)
        {
            this._userstoryService.UpdateEffortandEstimation(emp);
            //this._userstoryService.
            //EmployeeEffortEstimation emp = this._userstoryService.GetEffortData(empId, userStoryId);
            return RedirectToAction("Index");
        }


    }
}

MUMScrum.Web/Views/Project/Create.cshtml
@model MUMScrum.Model.Model.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>
       <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "Product Owner", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MUMScrum.Web/Views/Project/Delete.cshtml
@model MUMScrum.Model.Model.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">       
        <dt>
            @Html.DisplayNameFor(model => model.ProductOwner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductOwner.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>     
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MUMScrum.Web/Views/Project/Edit.cshtml
@model MUMScrum.Model.Model.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MUMScrum.Web/Views/Project/Index.cshtml
@model IEnumerable<MUMScrum.Model.Model.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New Project", "Create")
</p>
<table class="table">
    <tr>  
        <th>
            @Html.DisplayNameFor(model=>model.ProductOwner)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductOwner.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("UserStories", "UserStories", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            
        </td>
    </tr>
}

</table>

MUMScrum.Web/Views/Project/UserStories.cshtml
@model MUMScrum.Model.Model.Project

@{
    ViewBag.Title = "Details";
}
<h3 class="page-title">
    Details @Model.Name
</h3>
<h4>Project</h4>
<div class="row"> 
       @if (Model.userStoryList.Count == 0)
       {
        <h3>User Stories Not Found.</h3>
        @Html.ActionLink("Create", "Create", "UserStory")
       }
        <hr />
        @foreach (var item in Model.userStoryList)
        {
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat blue-madison">
                    <div class="visual">
                        <i class="fa fa-comments"></i>
                    </div>
                    <div class="details" >
                        <div  class="desc">
                            @item.Name
                        </div>
                        <div class="desc">
                            @item.Description
                        </div>
                        <div style="font-size:small; color:burlywood; float:right">
                            (@item.Status)
                        </div>
                        @*<div>
                                1349
                            </div>
                            <div class="desc">
                                New Feedbacks
                            </div>*@
                    </div>
                    <a class="more" href="/UserStory/Edit/@item.Id">
                        Edit <i class="m-icon-swapright m-icon-white"></i>
                    </a>
                </div>
            </div>
        }


           
</div>
    @Html.ActionLink("Back to List", "Index")
</p>